# Development image for the Quasar frontend
FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --ignore-scripts

ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=9000

EXPOSE 9000

CMD ["sh", "-c", "yarn install --frozen-lockfile --ignore-scripts && yarn run postinstall && yarn dev -- --hostname 0.0.0.0 --port 9000 --no-open"]

